#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_BOOT_MAX_IMG_SECTORS=256

# Enable fault injection hardening
CONFIG_BOOT_FIH_PROFILE_MEDIUM=y
# Enable ECDSA P256 signing/verification
CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
CONFIG_BOOT_SIGNATURE_TYPE_RSA=n
# Downgrade prevention
CONFIG_MCUBOOT_DOWNGRADE_PREVENTION=y